baseURL = 'https://jbedar.com'
locale = 'en-us'
title = 'Jeremiah Bedar'
theme = 'hugo-book'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  BookTheme = 'auto'
  BookSection = 'docs'
[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
      keepComments = false
    [minify.tdewolff.css]
      precision = 0
    [minify.tdewolff.js]
      precision = 0