baseURL = 'https://jbedar.com'
locale = 'en-us'
title = 'Jeremiah Bedar'
theme = 'hugo-book'

enableRobotsTXT = true
enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookSection = 'docs'
  BookSearch = true
  BookToC = true
  BookRepo = 'https://github.com/jbedar/jbedar.github.io'
  BookDateFormat = 'Jan 2, 2006'
  BookDescription = 'Systems & Network Administration documentation, home lab notes, and technical writeups by Jeremiah Bedar.'
  BookExperimentalFeatures = true
  
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
      keepComments = false
    [minify.tdewolff.css]
      precision = 0
    [minify.tdewolff.js]
      precision = 0